### ISSUE TITLE
Space gets replaced with dash

### ISSUE THREAD

**Issue by huubl** [shatstack/stylenames#32]
Hi,

I try to use this with a variable:

```:style="styleNames({ height: `calc( 100% - ${$height}px )` })"```

But it the first space gets replaced with a dash:

`style="height:calc(100%-- 90px);"`

Do you know how to get the right output? Thank you

**Comment by HugoDF** [comment]
This might be happening when doing the snake to kebab conversion, I'll have a look tomorrow.

**Comment by HugoDF** [comment]
So one way to get the right output is to get rid of the extra whitespace, but I'm not sure that ends up valid CSS.

I've created a fix though that I can release shortly.

**Comment by HugoDF** [comment]
Released in v1.3.3

**Comment by huubl** [comment]
That's fast! I tested it and it is working now. Thanks for helping!
